example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
# Implement Routings Here
from django.urls import path
from mywatchlist.views import show_watchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json
from mywatchlist.views import show_xml_by_id
from mywatchlist.views import show_json_by_id

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('html/', show_watchlist, name='show_watchlist'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
# Implement Routings Here
from audioop import add
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import status
from todolist.views import delete
from todolist.views import show_json_by_id
from todolist.views import add_task

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('change/<int:id>', status, name='status'),
    path('delete/<int:id>', delete, name='delete'),
    path('json', show_json_by_id, name='show_json_by_id'),
    path('add/', add_task, name='add_task'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# Create your views here.
def show_katalog(request):
    return render(request, "katalog.html", context)

data_barang_katalog = CatalogItem.objects.all()
context = {
    'list_barang': data_barang_katalog,
    'nama': 'Dhina Rotua Mutiara',
    'student_ID': '2106702182'
}

mywatchlist/views.py
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render
from mywatchlist.models import MyWatchList

# Create your views here.
def show_watchlist(request):
    return render(request, "mywatchlist.html", context)

data_watchlist = MyWatchList.objects.all()
context = {
    'list_mywatchlist': data_watchlist,
    'nama': 'Dhina Rotua Mutiara',
    'student_ID': '2106702182'
}

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request,id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request,id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
import datetime
from django.shortcuts import render
from todolist.models import Task
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from todolist.create_form import TaskForm
from django.http import HttpResponse
from django.core import serializers
from django.http.response import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_task = Task.objects.filter(user = request.user)
    context = {
        'list_task': data_task,
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            Task.objects.create(title=title, description=description, date=datetime.datetime.now(), user=request.user)
            return redirect('todolist:show_todolist')
    else:
        form = TaskForm()
        
    context = {'form':form}
    return render(request, 'create-task.html', context)

@login_required(login_url='/todolist/login/')
def status(request, id):
    task = Task.objects.get(id = id)
    task.is_finished = not(task.is_finished)
    task.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def delete(request, id):
    task = Task.objects.get(id = id)
    task.delete()
    return redirect('todolist:show_todolist')

def show_json_by_id(request):
    task = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", task), content_type="application/json")

@csrf_exempt
def add_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        task = Task.objects.create(title=title, description=description,date=datetime.date.today(), is_finished=False, user=request.user)

        context = {
            'fields':{
                'title':task.title,
                'description':task.description,
                'is_finished':task.is_finished,
                'date':task.date,
            },
            'pk':task.pk
        }
        
        return JsonResponse(context)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{student_ID}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 Assignment PBP</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{student_ID}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for watchlist in list_mywatchlist %}
    <tr>
        <th>{{watchlist.watched}}</th>
        <th>{{watchlist.title}}</th>
        <th>{{watchlist.rating}}</th>
        <th>{{watchlist.release_date}}</th>
        <th>{{watchlist.review}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>

todolist/templates/create-task.html
{% extends 'base.html' %}

 {% block content %}

 <style>
    .foto {
        background-image: url(https://wallpapercave.com/wp/wp4530778.jpg);
        height: 150vh;
        background-size: cover;
        background-position: center;
    }

    .tyrjlk {
        margin: auto;
    }
 </style>

 <body class="foto">
    <section class="tyrjlk">
    <br>
    <br>
    <br>
    <br>
  <h1 class="text text-white" style="text-align:center;">Create Task</h1>

    <form method="POST">
        {% csrf_token %}
        <table style="margin-left:auto;margin-right:auto;">  
            {{ form.as_table }}  
            <tr>  
                <td></td>
                <td><input type="submit" name="submit" value="Create"/></td>  
            </tr>  
        </table> 
    </form>
    </section>
</body>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login";>
    <form method="POST" action="">
        {% csrf_token %}
        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                  <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
          
                      <div class="mb-md-5 mt-md-4 pb-5">
          
                        <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                        <p class="text-white-50 mb-5">Please enter your username and password!</p>
          
                        <div class="form-outline form-white mb-4">
                          <input type="text" name="username" placeholder="Username" id="typeUsernameX" class="form-control" />
                          <label class="form-label" for="typeUsernameX">Username</label>
                        </div>
          
                        <div class="form-outline form-white mb-4">
                          <input type="password" name="password" placeholder="Password" id="typePasswordX" class="form-control" />
                          <label class="form-label" for="typePasswordX">Password</label>
                        </div>
                    
                        {% if messages %}
                            <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}

                        <input class="btn login_btn btn-outline-light btn-lg px-5" type="submit" value="Login"/>
          
                      </div>
          
                      <div>
                        <p class="mb-0">Don't have an account? <a href="{% url 'todolist:register' %}" class="text-white-50 fw-bold">Sign Up</a>
                        </p>
                      </div>
          
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
    </form>     

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">

        <form method="POST">  
            {% csrf_token %}  
            <!-- Section: Design Block -->
            <section class="background-radial-gradient overflow-hidden">
                <style>
                .background-radial-gradient {
                    background-color: hsl(218, 41%, 15%);
                    background-image: radial-gradient(650px circle at 0% 0%,
                        hsl(218, 41%, 35%) 15%,
                        hsl(218, 41%, 30%) 35%,
                        hsl(218, 41%, 20%) 75%,
                        hsl(218, 41%, 19%) 80%,
                        transparent 100%),
                    radial-gradient(1250px circle at 100% 100%,
                        hsl(218, 41%, 45%) 15%,
                        hsl(218, 41%, 30%) 35%,
                        hsl(218, 41%, 20%) 75%,
                        hsl(218, 41%, 19%) 80%,
                        transparent 100%);
                }
            
                #radius-shape-1 {
                    height: 220px;
                    width: 220px;
                    top: -60px;
                    left: -130px;
                    background: radial-gradient(#44006b, #ad1fff);
                    overflow: hidden;
                }
            
                #radius-shape-2 {
                    border-radius: 38% 62% 63% 37% / 70% 33% 67% 30%;
                    bottom: -60px;
                    right: -110px;
                    width: 300px;
                    height: 300px;
                    background: radial-gradient(#44006b, #ad1fff);
                    overflow: hidden;
                }
            
                .bg-glass {
                    background-color: hsla(0, 0%, 100%, 0.9) !important;
                    backdrop-filter: saturate(200%) blur(25px);
                }
                </style>
            
                <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
                <div class="row gx-lg-5 align-items-center mb-5">
                    <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
                    <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
                        Todo List <br />
                        <span style="color: hsl(218, 81%, 75%)">get reminded anytime!</span>
                    </h1>
                    </div>
            
                    <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                    <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                    <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>
            
                    <div class="card bg-glass">
                        <div class="card-body px-4 py-5 px-md-5">
                            <table>  
                                {{ form.as_table }}  
                                <tr>  
                                    <td></td>
                                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                                </tr>  
                            </table>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </section>
            <!-- Section: Design Block -->
        </form>

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

 {% block content %}
<head>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(() => {
            const card = (data) => `<div class="card">
                <h4 class="card-title">${data.fields.title}</h4>
                <p class="card-text">
                    ${data.fields.date} 
                    <br> 
                    ${data.fields.description}
                    </p>
                    
                    <p class="card-text">
                        <small class="text-muted">
                            ${data.fields.is_finished ? 'Selesai' : 'Belum Selesai'}
                        </small>
                    </p>
                    <td>
                        <button><a href="/todolist/change/${data.pk}">Change Status</a></button>
                        <button><a href="/todolist/delete/${data.pk}">Delete</a></button>
                    </td>
                                
                </div>`
                                
            const addCard = (data) => {
                return $('.box').append(card(data))
            }   
        
            $.get('/todolist/json', function (todo) {
                todo.map((task) => {
                    addCard(task)
                })
            })

            $(`#add-task`).click(function(){
                if ($('#title').val() && $('#description').val()){
                    $.post('/todolist/add/', {
                            title: $('#title').val(),
                            description: $('#description').val(),
                        },
                        function(res, status){
                            if(status == 'success'){
                                addCard(res)
                                $('#title').val('')
                                $('#description').val('')
                            }
                        },
                    )
                    return false
                }
            })
        });
    
    </script>
</head>

<section  class="box">
    <div>
        <h2 style="color:rgb(100, 100, 255); text-align:center" >Selamat datang, {{ user.get_username }}!</h2>
    </div>

    <br>
    <br>

    <div class="d-grid gap-2 d-md-block">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Tambah Task Baru
        </button>
        <button class="btn btn-danger" type="button"><a href="{% url 'todolist:logout' %}" style="color: rgb(255, 255, 255)">Logout</a></button>
    </div>
</section>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">New Task</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="POST">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Title:</td>
                        <td><input type="text" name="title" class="form-control" id="title"></td>
                    </tr>
                            
                    <tr>
                        <div>
                            <td>Description: </td>
                            <td><input type="text" name="description" class="form-control" id="description"></td>
                        </div>
                    </tr>
                </table>
            </form>
        </div>
        <div class="modal-footer">
          <button type="submit" id="add-task" name="submit" class="btn btn-primary" data-bs-dismiss="modal">Create</button>
        </div>
      </div>
    </div>
  </div>



<style>
    body {
        background-color:rgb(217, 255, 246);
    }
    .box {
        width:500px;
        margin: 50px auto;
        padding:5px;
        border-radius: 3px;
        align-content: center;
    }
    .card {
        background-color:rgb(255, 220, 246);
        border-radius: 3px;
        padding: 10px; 
        margin: 10px;
    }
    .card:hover {
        transform: scale(1.02);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }
    .card-button {
        display: inline-flex;
        justify-content: right;
    }
    .outside-button {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>

 {% endblock content %}